### PR TITLE
Create SPEAKERS-AND-TOPICS.md

### PR DESCRIPTION
**Pull request by groovecoder**

### CODE REVIEW

**Comment by groovecoder** [comment]
@seejessicacode @rhoegg @amandaharlin how does this look for a start?

**Comment by seejessicacode** [comment]
I like it. I'm trying to think up a folder structure though.

**Comment by groovecoder** [comment]
I think the easiest thing to start with will be a single file in the root of the repo. So we can just tell people to go straight to the file and edit it.

That way we can let speakers create a natural/evolving grouping, and then if the file gets un-wieldy we can split it up into folders?

**Comment by seejessicacode** [comment]
Sounds fair! We'll try it and see how it looks in a  month.

**Pull request merged**
